import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<title>YTÜ Mentorluk Kulübü</title>
				<link rel='shortcut icon' href='logo.png' type='image/x-icon' />
			</head>
			<body>{children}</body>
		</html>
	);
}
